#!/usr/bin/env python3
"""Extract additional Tantrāloka/Tantrasāra loci from the volume into corpus/extracts."""
from __future__ import annotations
import re
from pathlib import Path

VOL = Path("/mnt/HC_Volume_106959365/root/projects/source-library/tantra/abhinavagupta")
OUT = Path(__file__).resolve().parents[1] / "corpus/extracts" / "TA_EXTRA_HITS.md"

PATTERNS = [
    r"śabdarāśi",
    r"mātṛkā",
    r"mālinī",
    r"varṇa",
    r"prāṇāyāma",
    r"dvādaś",
    r"nyāsa",
    r"vaikhar",
    r"madhyamā",
    r"parāvāc",
    r"haṃsa",
    r"saḥ",
]

def main():
    files = sorted(VOL.glob("ahnika-*.txt"))
    # prefer smaller curated files + ahnika-03 short + ahnika-15 long
    hits = []
    for f in files:
        text = f.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()
        for i, line in enumerate(lines, 1):
            low = line.lower()
            for pat in PATTERNS:
                if re.search(pat, low):
                    start = max(0, i - 2)
                    end = min(len(lines), i + 2)
                    snippet = "\n".join(lines[start:end])
                    hits.append((f.name, i, pat, snippet))
                    break
    # cap volume of output
    hits = hits[:400]
    parts = ["# TA_EXTRA_HITS — auto extract\n",
             f"> Generated by scripts/deepdive_tantraloka.py from {VOL}\n",
             f"> Hits written: {len(hits)} (capped)\n"]
    by_file = {}
    for fn, ln, pat, snip in hits:
        by_file.setdefault(fn, []).append((ln, pat, snip))
    for fn, rows in sorted(by_file.items()):
        parts.append(f"\n## {fn} ({len(rows)} hits)\n")
        for ln, pat, snip in rows[:30]:
            parts.append(f"\n### {fn}:{ln} [{pat}]\n```\n{snip}\n```\n")
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT} with {len(hits)} hits from {len(by_file)} files")

if __name__ == "__main__":
    main()
